Repository morib-in/Morib-Server, pull requests merged in 2024-07, with the labels that each got.

#17 [Feat] 소셜 로그인, 회원가입 구현
  jaksim/build.gradle
  jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java
  jaksim/src/main/java/org/sopt/jaksim/auth/filter/JwtAuthenticationFilter.java
  jaksim/src/main/java/org/sopt/jaksim/auth/jwt/JwtTokenProvider.java
  jaksim/src/main/java/org/sopt/jaksim/auth/jwt/JwtValidationType.java
  jaksim/src/main/java/org/sopt/jaksim/global/common/Constants.java
  jaksim/src/main/java/org/sopt/jaksim/global/common/HealthCheckController.java
  jaksim/src/main/java/org/sopt/jaksim/global/exception/GlobalExceptionHandler.java
  jaksim/src/main/java/org/sopt/jaksim/global/exception/IOException.java
  jaksim/src/main/java/org/sopt/jaksim/global/exception/OAuthException.java
  jaksim/src/main/java/org/sopt/jaksim/global/message/ErrorMessage.java
  jaksim/src/main/java/org/sopt/jaksim/socket/WebSocketConfig.java
  jaksim/src/main/java/org/sopt/jaksim/socket/WebSocketHandler.java
  jaksim/src/main/java/org/sopt/jaksim/user/api/SocialLoginTempController.java
  jaksim/src/main/java/org/sopt/jaksim/user/api/UserApi.java
  jaksim/src/main/java/org/sopt/jaksim/user/api/UserApiController.java
  jaksim/src/main/java/org/sopt/jaksim/user/domain/User.java
  jaksim/src/main/java/org/sopt/jaksim/user/dto/Tokens.java
  jaksim/src/main/java/org/sopt/jaksim/user/dto/UserInfo.java
  jaksim/src/main/java/org/sopt/jaksim/user/dto/request/UserSignUpRequest.java
  jaksim/src/main/java/org/sopt/jaksim/user/dto/response/UserSignUpResponse.java
  jaksim/src/main/java/org/sopt/jaksim/user/facade/UserFacade.java
  jaksim/src/main/java/org/sopt/jaksim/user/service/UserService.java
Labels: feat, fix

#19 Feat [#18] Socket.io를 이용한 웹소켓 구현
  jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java
  jaksim/src/main/java/org/sopt/jaksim/socket/config/SocketIoConfig.java
  jaksim/src/main/java/org/sopt/jaksim/socket/config/SocketIoServerLifeCycle.java
  jaksim/src/main/java/org/sopt/jaksim/socket/config/SocketModule.java
  jaksim/src/main/java/org/sopt/jaksim/socket/controller/MessageController.java
  jaksim/src/main/java/org/sopt/jaksim/socket/controller/SocketIOController.java
  jaksim/src/main/java/org/sopt/jaksim/socket/dto/WebSocketRequest.java
  jaksim/src/main/java/org/sopt/jaksim/socket/dto/WebSocketResponse.java
  jaksim/src/main/java/org/sopt/jaksim/socket/message/Message.java
  jaksim/src/main/java/org/sopt/jaksim/socket/message/MessageType.java
  jaksim/src/main/java/org/sopt/jaksim/socket/repository/RedisSocketMessageRepository.java
  jaksim/src/main/java/org/sopt/jaksim/socket/service/MessageService.java
  jaksim/src/main/java/org/sopt/jaksim/socket/service/SocketService.java
Labels: feat, socket

#21 Feat [#20] Amazon S3 설정 & 시큐리티 설정 클래스 수정
  jaksim/build.gradle
  jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java
  jaksim/src/main/java/org/sopt/jaksim/global/common/S3Service.java
  jaksim/src/main/java/org/sopt/jaksim/global/config/AwsConfig.java
  jaksim/src/main/java/org/sopt/jaksim/user/api/UserApiController.java
Labels: feat, deploy

#23 Feat [#22] 기본 엔티티 클래스 세팅
  jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java
  jaksim/src/main/java/org/sopt/jaksim/category/domain/Category.java
  jaksim/src/main/java/org/sopt/jaksim/category/domain/CategoryTask.java
  jaksim/src/main/java/org/sopt/jaksim/global/config/RedisConfig.java
  jaksim/src/main/java/org/sopt/jaksim/mset/domain/CategoryMset.java
  jaksim/src/main/java/org/sopt/jaksim/mset/domain/Mset.java
  jaksim/src/main/java/org/sopt/jaksim/mset/domain/TaskMset.java
  jaksim/src/main/java/org/sopt/jaksim/task/domain/Task.java
  jaksim/src/main/java/org/sopt/jaksim/task/domain/TaskTimer.java
  jaksim/src/main/java/org/sopt/jaksim/task/domain/Todo.java
  jaksim/src/main/java/org/sopt/jaksim/task/domain/TodoTask.java
  jaksim/src/main/java/org/sopt/jaksim/task/domain/UserTimer.java
  jaksim/src/main/java/org/sopt/jaksim/user/domain/Permission.java
  jaksim/src/main/java/org/sopt/jaksim/user/domain/PermissionLevel.java
  jaksim/src/main/java/org/sopt/jaksim/user/domain/User.java
Labels: feat

#28 Feat [#26] 전체 작업시간 조회 API
  jaksim/build.gradle
  jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java
  jaksim/src/main/java/org/sopt/jaksim/category/domain/Category.java
  jaksim/src/main/java/org/sopt/jaksim/global/common/DateUtil.java
  jaksim/src/main/java/org/sopt/jaksim/global/exception/DateTimeParseException.java
  jaksim/src/main/java/org/sopt/jaksim/global/exception/GlobalExceptionHandler.java
  jaksim/src/main/java/org/sopt/jaksim/global/message/ErrorMessage.java
  jaksim/src/main/java/org/sopt/jaksim/global/message/SuccessMessage.java
  jaksim/src/main/java/org/sopt/jaksim/mset/domain/CategoryMset.java
  jaksim/src/main/java/org/sopt/jaksim/mset/domain/Mset.java
  jaksim/src/main/java/org/sopt/jaksim/mset/domain/TaskMset.java
  jaksim/src/main/java/org/sopt/jaksim/task/api/TaskApiController.java
  jaksim/src/main/java/org/sopt/jaksim/task/api/TimerApiController.java
  jaksim/src/main/java/org/sopt/jaksim/task/domain/Task.java
  jaksim/src/main/java/org/sopt/jaksim/task/domain/TaskTimer.java
  jaksim/src/main/java/org/sopt/jaksim/task/domain/Todo.java
  jaksim/src/main/java/org/sopt/jaksim/task/domain/TodoTask.java
  jaksim/src/main/java/org/sopt/jaksim/task/domain/UserTimer.java
  jaksim/src/main/java/org/sopt/jaksim/task/dto/FetchTitleRequest.java
  jaksim/src/main/java/org/sopt/jaksim/task/dto/FetchTitleResponse.java
  jaksim/src/main/java/org/sopt/jaksim/task/dto/StopTimerRequest.java
  jaksim/src/main/java/org/sopt/jaksim/task/dto/TotalTimeTodayResponse.java
  jaksim/src/main/java/org/sopt/jaksim/task/repository/TaskRepository.java
  jaksim/src/main/java/org/sopt/jaksim/task/repository/TaskTimerRepository.java
  jaksim/src/main/java/org/sopt/jaksim/task/repository/UserTimerRepository.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/TaskService.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/TaskTimerService.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/UserTimerService.java
  jaksim/src/main/java/org/sopt/jaksim/user/api/UserApiController.java
  jaksim/src/main/java/org/sopt/jaksim/user/domain/Permission.java
  jaksim/src/main/java/org/sopt/jaksim/user/domain/User.java
  jaksim/src/main/java/org/sopt/jaksim/user/facade/UserFacade.java
  jaksim/src/main/java/org/sopt/jaksim/user/service/UserService.java
Labels: feat

#31 Feat [#30] 구간에 해당하는 카테고리, 태스크 조회 API 구현
  jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApiController.java
  jaksim/src/main/java/org/sopt/jaksim/category/domain/Category.java
  jaksim/src/main/java/org/sopt/jaksim/category/domain/CategoryTask.java
  jaksim/src/main/java/org/sopt/jaksim/category/dto/CategoryTaskLink.java
  jaksim/src/main/java/org/sopt/jaksim/category/dto/FilteredResourceResponse.java
  jaksim/src/main/java/org/sopt/jaksim/category/repository/CategoryRepository.java
  jaksim/src/main/java/org/sopt/jaksim/category/repository/CategoryTaskRepository.java
  jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryService.java
  jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryTaskFacade.java
  jaksim/src/main/java/org/sopt/jaksim/global/common/DateUtil.java
  jaksim/src/main/java/org/sopt/jaksim/task/domain/Todo.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/TaskService.java
Labels: feat, fix

#40 Feat [#39] 홈뷰, URL Fetch, 모립세트 불러오기 API
  jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java
  jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApiController.java
  jaksim/src/main/java/org/sopt/jaksim/category/dto/CategoryMsetLinkResponse.java
  jaksim/src/main/java/org/sopt/jaksim/category/facade/CategoryMsetFacade.java
  jaksim/src/main/java/org/sopt/jaksim/category/facade/CategoryTaskFacade.java
  jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryService.java
  jaksim/src/main/java/org/sopt/jaksim/mset/api/MsetApiController.java
  jaksim/src/main/java/org/sopt/jaksim/mset/repository/CategoryMsetRepository.java
  jaksim/src/main/java/org/sopt/jaksim/mset/service/CategoryMsetService.java
  jaksim/src/main/java/org/sopt/jaksim/mset/service/MsetService.java
  jaksim/src/main/java/org/sopt/jaksim/task/api/TimerApiController.java
  jaksim/src/main/java/org/sopt/jaksim/task/domain/Todo.java
  jaksim/src/main/java/org/sopt/jaksim/task/domain/TodoTask.java
  jaksim/src/main/java/org/sopt/jaksim/task/domain/UserTimer.java
  jaksim/src/main/java/org/sopt/jaksim/task/dto/StartTimerRequest.java
  jaksim/src/main/java/org/sopt/jaksim/task/dto/TaskInTodoCard.java
  jaksim/src/main/java/org/sopt/jaksim/task/dto/TodoCardResponse.java
  jaksim/src/main/java/org/sopt/jaksim/task/repository/TaskTimerRepository.java
  jaksim/src/main/java/org/sopt/jaksim/task/repository/TodoRepository.java
  jaksim/src/main/java/org/sopt/jaksim/task/repository/TodoTaskRepository.java
  jaksim/src/main/java/org/sopt/jaksim/task/repository/UserTimerRepository.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/TaskService.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/TaskTimerService.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/TodoService.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/TodoTaskService.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/UserTimerService.java
  jaksim/src/main/java/org/sopt/jaksim/user/api/UserApi.java
Labels: feat, fix

#43 Feat [#42] 타이머 API 수정
  jaksim/src/main/java/org/sopt/jaksim/global/config/SwaggerConfig.java
  jaksim/src/main/java/org/sopt/jaksim/task/api/TimerApiController.java
  jaksim/src/main/java/org/sopt/jaksim/task/domain/TaskTimer.java
  jaksim/src/main/java/org/sopt/jaksim/task/domain/UserTimer.java
  jaksim/src/main/java/org/sopt/jaksim/task/dto/StopTimerRequest.java
  jaksim/src/main/java/org/sopt/jaksim/task/dto/TotalTimeTodayResponse.java
  jaksim/src/main/java/org/sopt/jaksim/task/repository/TaskTimerRepository.java
  jaksim/src/main/java/org/sopt/jaksim/task/repository/UserTimerRepository.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/TaskService.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/TaskTimerService.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/TodoService.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/TodoTaskService.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/UserTimerService.java
Labels: fix

#56 Fix [#55] corsFilterRegistrationBean 삭제
  jaksim/src/main/java/org/sopt/jaksim/auth/WebSecurityConfig.java
Labels: fix

#136 Fix [#135] 카테고리 생성 시 startDate null 핸들링
  jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryService.java
Labels: feat, fix

#141 Fix [#139] Todo 생성 API userId 검사 로직 추가
  jaksim/src/main/java/org/sopt/jaksim/task/service/TodoService.java
Labels: fix

#142 Fix [#140] 카테고리 삭제 API null 핸들링 코드 추가
  jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApiController.java
  jaksim/src/main/java/org/sopt/jaksim/category/facade/CategoryMsetFacade.java
  jaksim/src/main/java/org/sopt/jaksim/category/facade/CategoryTaskFacade.java
  jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryService.java
  jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryTaskService.java
  jaksim/src/main/java/org/sopt/jaksim/mset/service/CategoryMsetService.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/TaskService.java
Labels: fix

#146 Fix [#144] 카테고리 생성 시 mset이 없어도 생성될 수 있게 null 핸들링
  jaksim/src/main/java/org/sopt/jaksim/mset/service/MsetService.java
Labels: fix

#148 Fix [#147] 홈뷰 전체조회 API 태스크 Id 내림차순으로 정렬
  jaksim/src/main/java/org/sopt/jaksim/category/facade/CategoryTaskFacade.java
Labels: fix

#145 Fix[#143] 스웨거 추가 적용
  jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApi.java
  jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApiController.java
  jaksim/src/main/java/org/sopt/jaksim/mset/api/MsetApi.java
  jaksim/src/main/java/org/sopt/jaksim/mset/api/MsetApiController.java
Labels: feat, chore

#150 Bug [#149] NonUniqueResultException
  jaksim/src/main/java/org/sopt/jaksim/task/repository/TaskTimerRepository.java
  jaksim/src/main/java/org/sopt/jaksim/task/repository/TodoTaskRepository.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/TaskTimerService.java
  jaksim/src/main/java/org/sopt/jaksim/task/service/TodoTaskService.java
Labels: bug, fix

#152 Fix [#151] 카테고리 조회 정렬 로직 추가
  jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryService.java
Labels: fix
